run:
  timeout: 2m
  allow-parallel-runners: true

linters:
  disable-all: true
  enable:
    - unused
    - gofmt
    - staticcheck
    - revive
    - godot
    - whitespace
    - goimports
    - gosimple
    - errcheck
    - unconvert
    - gocritic
    - gosec
    - gocyclo

linters-settings:
  gofmt:
    simplify: true
  staticcheck:
    checks: [ "all" ]
  godot:
    scope: declarations
    capital: true
  goimports:
    local-prefixes: "github.com/auth0/terraform-provider-auth0"
  revive:
    rules:
      - name: package-comments
        severity: warning
        disabled: true
  gosec:
    excludes:
      # G101 is "Potential hardcoded credentials"
      # We exclude it as we need to set dummy
      # credentials within our tests.
      - G101
  gocyclo:
    min-complexity: 30 # This is the default but our goal is to take this down to 15.

issues:
  exclude-use-default: false
  fix: true
