run:
  go: "1.19"

linters:
  disable-all: true
  enable:
    - unused
    - gofmt
    - staticcheck
    - revive
    - godot
    - whitespace
    - goimports
    - gosimple
    - errcheck
    - unconvert

linters-settings:
  gofmt:
    simplify: true
  staticcheck:
    checks: [ "all" ]
  godot:
    scope: declarations
    capital: true
  goimports:
    local-prefixes: "github.com/auth0/terraform-provider-auth0"
  revive:
    rules:
      - name: package-comments
        severity: warning
        disabled: true

issues:
  exclude-use-default: false
