# See http://pre-commit.com/
repos:
  - repo: local
    hooks:
      - id: golangci-lint
        name: Go Linter
        description: Runs `golangci-lint`, requires https://github.com/golangci/golangci-lint
        language: system
        entry: make lint
        files: '(?<!\.pb)\.go$'
