blank_issues_enabled: false
contact_links:
  - name: 🤔 Help & Questions
    url: https://community.auth0.com/c/help/6
    about: Ask general support or usage questions in the Auth0 Community forums
  - name: 📖 Terraform Provider Documentation
    url: https://registry.terraform.io/providers/auth0/auth0/latest/docs
    about: Check the terraform provider documentation for in-depth overview of all the available resources
