name: Test Tenant Cleanup

concurrency:
  group: one-at-time
  cancel-in-progress: false

on: [workflow_dispatch]

jobs:
  sweep:
    name: Sweep
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Set up Go
        uses: actions/setup-go@7b8cf10d4e4a01d4992d18a89f4d7dc5a3e6d6f4 # v4.3.0
        with:
          go-version-file: go.mod
          check-latest: true

      - name: Sweep
        run: make test-sweep
        env:
          AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
          AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
